FROM ruby:2.6.3-alpine
RUN apk add --no-cache --update build-base \
  linux-headers \
  git \
  postgresql-dev \
  nodejs \
  tzdata


# environment vars must be included in heroku.yml and dockerfile
ARG DATABASE_URL="postgres://postgres@db"
ARG RAILS_ENV=production

WORKDIR /myapp
# RUN rm -f /myapp/tmp/pids/server.pid
COPY Gemfile /myapp/Gemfile
COPY Gemfile.lock /myapp/Gemfile.lock
RUN gem install bundler && bundle install
COPY . /myapp

# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh


EXPOSE 3000

# Start the main process.
CMD ["rails", "assets:precompile"]
# CMD ["rails", "db:create"]
# CMD ["rails", "db:migrate:status"]
# CMD ["rails", "db:migrate"]
# CMD ["rails", "db:seed"]
CMD ["rails", "server", "-b", "0.0.0.0"] 
